import type { BuildPreset } from "@/types/garage.types";

export const CURATED_PRESETS: BuildPreset[] = [
  {
    id: "preset-elantra-n-tcr",
    name: "Elantra N TCR Official Spec",
    koreanName: "아반떼 N TCR 공식 레이스 규격",
    category: "track",
    badgeTag: "WTCR / TCR KOREA",
    countryCode: "KR",
    targetDiscipline: "Touring Car Championship / Sprint",
    vehicleId: "hyundai-elantra-n-cn7-mt",
    description:
      "Официальный регламент кузовного чемпионата TCR: двухлитровый турбо Theta II N с боевой прошивкой MoTeC M150, облегченным маховиком, 6-поршневыми суппортами AP Racing Pro 5000R и шведской подвеской Öhlins DFV.",
    highlights: [
      "Theta II 2.0T Race Calibration",
      "AP Racing Radi-CAL 6-Pot (378mm)",
      "Öhlins Road & Track Dual Flow Valve",
      "Akrapovič Evolution Titanium",
      "Cusco 1.5-Way Multi-Plate LSD",
    ],
    slots: {
      engineId: "eng-g4kh-theta-20t",
      transId: "tr-m6gf2-6mt-n",
      diffId: "diff-cusco-type-rs-15way",
      turboId: "turbo-stage2-hybrid",
      intakeId: "intake-fmic-wagner",
      exhaustId: "exhaust-akrapovic-evo",
      brakeId: "brake-ap-racing-pro5000",
      suspensionId: "suspension-ohlins-rt",
      ecuId: "ecu-motec-m150",
      mountId: "mount-poly-95a-track",
      coolingId: "cooling-csf-triple-pass",
    },
    specsEstimate: {
      powerHp: 385,
      torqueNm: 495,
      weightKg: 1260,
      zeroToHundredSec: "4.1s",
      topSpeedKmh: 275,
    },
  },
  {
    id: "preset-golf-r-daza-rs",
    name: "Golf R Mk7.5 \"DAZA RS\" 5-Cyl Swap",
    koreanName: "골프 R DAZA 2.5 TFSI 5기통 스왑",
    category: "time-attack",
    badgeTag: "TIME ATTACK 650HP",
    countryCode: "DE",
    targetDiscipline: "Nürburgring Record / Track Day",
    vehicleId: "volkswagen-golf-r-mk7",
    description:
      "Ультимативный свап платформы MQB: легендарный 5-цилиндровый двигатель Audi 2.5 TFSI DAZA в кузове Golf R с роботизированной КПП DQ500, улиткой Garrett G30-770 и углерод-керамическими тормозами Brembo CCB.",
    highlights: [
      "Audi DAZA 2.5 TFSI Inline-5 Swap",
      "Garrett G30-770 Big Single (+275 HP)",
      "DQ500 7-Speed Reinforced DSG",
      "Brembo Carbon-Ceramic Matrix (400mm)",
      "Eventuri Carbon Airbox + KW V3",
    ],
    slots: {
      engineId: "eng-daza-25-tfsi-audi",
      transId: "tr-dq500-7dsg-vag",
      drivelineId: "dl-vag-haldex-awd",
      turboId: "turbo-garrett-g30-770",
      intakeId: "intake-eventuri-carbon",
      exhaustId: "exhaust-akrapovic-evo",
      brakeId: "brake-carbon-ceramic-ccb",
      suspensionId: "suspension-kw-v3",
      ecuId: "ecu-motec-m150",
      mountId: "mount-poly-95a-track",
      coolingId: "cooling-csf-triple-pass",
    },
    specsEstimate: {
      powerHp: 675,
      torqueNm: 780,
      weightKg: 1440,
      zeroToHundredSec: "2.8s",
      topSpeedKmh: 325,
    },
  },
  {
    id: "preset-silvia-s15-formula-drift",
    name: "Silvia S15 \"Formula Drift Pro Spec\"",
    koreanName: "실비아 S15 포뮬러 드리프트 V8 프로",
    category: "drift",
    badgeTag: "PRO DRIFT 850HP",
    countryCode: "JP",
    targetDiscipline: "Formula Drift / D1GP Competition",
    vehicleId: "nissan-silvia-s15-spec-r",
    description:
      "Дрифт-корч высшего эшелона: свап американского 6.2L V8 LS3 со шнековым компрессором Whipple 2.9L, КПП Tremec T56, быстросменным редуктором Winters Quick-Change и цельнофрезерованными опорами Sikky Billet.",
    highlights: [
      "GM LS3 6.2L V8 + Whipple 2.9L SC",
      "Winters V8 Pro Quick-Change Rear End",
      "Tremec T56 Magnum 6-Speed Manual",
      "Sikky Solid Billet 6061 Aluminum Mounts",
      "Tomei Titanium Straight Pipe (108 dB)",
    ],
    slots: {
      engineId: "eng-ls3-gm",
      transId: "tr-tremec-t56-magnum",
      diffId: "diff-winters-quick-change",
      turboId: "turbo-whipple-29l-supercharger",
      intakeId: "intake-cold-air-aem",
      exhaustId: "exhaust-tomei-titanium",
      brakeId: "brake-brembo-gt-6pot",
      suspensionId: "suspension-bc-racing-br",
      ecuId: "ecu-haltech-elite2500",
      mountId: "mount-billet-solid-6061",
      coolingId: "cooling-setrab-dual-oil",
    },
    specsEstimate: {
      powerHp: 740,
      torqueNm: 920,
      weightKg: 1210,
      zeroToHundredSec: "3.2s",
      topSpeedKmh: 295,
    },
  },
  {
    id: "preset-miata-k24-touge",
    name: "Miata NA \"K24 Touge Screamer\"",
    koreanName: "미아타 NA 혼다 K24A2 고회전 스왑",
    category: "touge",
    badgeTag: "TOUGE / 9000 RPM",
    countryCode: "JP",
    targetDiscipline: "Touge Attack / Mountain Pass",
    vehicleId: "mazda-miata-na-18",
    description:
      "Легковесный убийца суперкаров для горных серпантинов: высокооборотистый атмосферный 2.4L Honda K24A2 с индивидуальными дросселями ITB, трубчатым подрамником K-Tuned, отсечкой 9,000 RPM и весом менее тонны.",
    highlights: [
      "Honda K24A2 i-VTEC NA Swap",
      "Individual Throttle Bodies (ITB) Carbon",
      "K-Tuned Tubular K-Swap Subframe",
      "Cusco Type-RS 1.5-Way LSD",
      "Öhlins DFV Track Coilovers",
    ],
    slots: {
      engineId: "eng-k24a2-honda",
      transId: "tr-miata-6mt-mazda",
      diffId: "diff-cusco-type-rs-15way",
      turboId: "turbo-itb-carbon-plenum",
      intakeId: "intake-eventuri-carbon",
      exhaustId: "exhaust-tomei-titanium",
      brakeId: "brake-sport-pads-brembo",
      suspensionId: "suspension-ohlins-rt",
      ecuId: "ecu-haltech-elite2500",
      mountId: "mount-kswap-subframe-ktuned",
      coolingId: "cooling-mishimoto-xline",
    },
    specsEstimate: {
      powerHp: 275,
      torqueNm: 285,
      weightKg: 935,
      zeroToHundredSec: "4.4s",
      topSpeedKmh: 245,
    },
  },
  {
    id: "preset-stinger-gt-track-edition",
    name: "Stinger GT 3.3T \"Biarritz Track 6MT\"",
    koreanName: "스팅어 GT 3.3T 수동변속기 트랙 에디션",
    category: "track",
    badgeTag: "KDM GT / 6MT SWAP",
    countryCode: "KR",
    targetDiscipline: "High-Speed Highway / Track Day",
    vehicleId: "kia-stinger-gt-ck",
    description:
      "Эксклюзивная конверсия фастбэка: битурбо Lambda II 3.3T с кастомным свапом МКПП Tremec T56 вместо 8AT, турбинами BorgWarner EFR 7163 Twin-Scroll, блокировкой OS Giken Super Lock и управляемым выхлопом Armytrix.",
    highlights: [
      "Custom 6-Speed Manual (Tremec T56 Swap)",
      "BorgWarner EFR 7163 Twin-Scroll Turbos",
      "OS Giken Super Lock 2-Way LSD",
      "Armytrix Valvetronic Active Exhaust",
      "KW Variant 3 Inox-Line Suspension",
    ],
    slots: {
      engineId: "eng-g6dp-lambda-33t",
      transId: "tr-tremec-t56-magnum",
      diffId: "diff-osgiken-superlock-2way",
      turboId: "turbo-borgwarner-efr-7163",
      intakeId: "intake-fmic-wagner",
      exhaustId: "exhaust-armytrix-valvetronic",
      brakeId: "brake-brembo-gt-6pot",
      suspensionId: "suspension-kw-v3",
      ecuId: "ecu-stage2-burble",
      mountId: "mount-poly-70a-street",
      coolingId: "cooling-setrab-dual-oil",
    },
    specsEstimate: {
      powerHp: 545,
      torqueNm: 710,
      weightKg: 1720,
      zeroToHundredSec: "3.5s",
      topSpeedKmh: 310,
    },
  },
  {
    id: "preset-supra-a80-wangan",
    name: "Supra A80 \"Midnight Wangan 1000\"",
    koreanName: "수프라 A80 완간 미드나잇 1000마력",
    category: "drag",
    badgeTag: "WANGAN / 1000HP",
    countryCode: "JP",
    targetDiscipline: "Highway Roll Racing / Drag Strip",
    vehicleId: "toyota-supra-a80-turbo",
    description:
      "Икона японской полуночной лиги: легендарный 2JZ-GTE с гигантским сингл-турбо Precision 6266 Gen 2 (до 850+ л.с.), пуленепробиваемой МКПП Getrag V160, 33-шлицевыми приводами DSS 1000HP и сухим картером Peterson.",
    highlights: [
      "2JZ-GTE + Precision 6266 Gen 2 CEA (2.5 bar)",
      "Getrag V160 6-Speed Manual",
      "The Driveshaft Shop Pro-Level 1000HP Axles",
      "Peterson 4-Stage Dry Sump Oil System",
      "AP Racing Radi-CAL Brakes (378mm)",
    ],
    slots: {
      engineId: "eng-2jz-gte-toyota",
      transId: "tr-v160-6mt-toyota",
      diffId: "diff-dss-axles-1000hp-kit",
      turboId: "turbo-precision-6266-gen2",
      intakeId: "intake-fmic-wagner",
      exhaustId: "exhaust-tomei-titanium",
      brakeId: "brake-ap-racing-pro5000",
      suspensionId: "suspension-kw-v3",
      ecuId: "ecu-haltech-elite2500",
      mountId: "mount-poly-95a-track",
      coolingId: "cooling-peterson-dry-sump",
    },
    specsEstimate: {
      powerHp: 780,
      torqueNm: 860,
      weightKg: 1490,
      zeroToHundredSec: "2.9s",
      topSpeedKmh: 345,
    },
  },
  {
    id: "preset-bmw-m3-e46-csl",
    name: "BMW M3 E46 \"CSL Track Pure\"",
    koreanName: "BMW M3 E46 CSL 순수 트랙 에디션",
    category: "track",
    badgeTag: "CSL ATMO / 8200 RPM",
    countryCode: "DE",
    targetDiscipline: "Circuit Racing / Nordschleife",
    vehicleId: "bmw-m3-e46",
    description:
      "Чистокровный баварский трек-тул: атмосферный высокооборотистый S54B32 с карбоновым ресивером Eventuri, индивидуальными дросселями ITB, автоспортивным блоком MoTeC M150, дисковой блокировкой Cusco и титаном Akrapovič.",
    highlights: [
      "S54B32 3.2L Inline-6 High-Rev (8,200 RPM)",
      "Carbon ITB Plenum + Eventuri Intake",
      "Akrapovič Titanium Evolution Line",
      "AP Racing Radi-CAL Competition BBK",
      "Öhlins Road & Track Dual Flow Valve",
    ],
    slots: {
      engineId: "eng-s54b32-bmw",
      transId: "tr-gs6-53dz-bmw",
      diffId: "diff-cusco-type-rs-15way",
      turboId: "turbo-itb-carbon-plenum",
      intakeId: "intake-eventuri-carbon",
      exhaustId: "exhaust-akrapovic-evo",
      brakeId: "brake-ap-racing-pro5000",
      suspensionId: "suspension-ohlins-rt",
      ecuId: "ecu-motec-m150",
      mountId: "mount-poly-95a-track",
      coolingId: "cooling-csf-triple-pass",
    },
    specsEstimate: {
      powerHp: 415,
      torqueNm: 405,
      weightKg: 1320,
      zeroToHundredSec: "4.0s",
      topSpeedKmh: 290,
    },
  },
  {
    id: "preset-mustang-gt-whipple",
    name: "Mustang GT S550 \"Whipple Predator 750\"",
    koreanName: "머스탱 GT 5.0 위플 슈퍼차저 750마력",
    category: "drag",
    badgeTag: "V8 SC / 750HP",
    countryCode: "US",
    targetDiscipline: "Drag Strip / Street Muscle",
    vehicleId: "ford-mustang-gt-s550",
    description:
      "Американская грубая сила: 5.0L Coyote V8 с приводным шнековым нагнетателем Whipple 2.9L Gen 5, МКПП Tremec T56 Magnum, басовитой трассой Borla ATAK Long-Tube и 1000-сильными приводами DSS.",
    highlights: [
      "5.0L Coyote Gen 3 + Whipple 2.9L SC",
      "Tremec T56 Magnum 6-Speed Heavy Duty",
      "Borla ATAK Long-Tube Headers + X-Pipe",
      "DSS Pro-Level 1000HP Axles",
      "Brembo GT 6-Piston Big Brake Kit",
    ],
    slots: {
      engineId: "eng-coyote-50-ford",
      transId: "tr-tremec-t56-magnum",
      diffId: "diff-dss-axles-1000hp-kit",
      turboId: "turbo-whipple-29l-supercharger",
      intakeId: "intake-cold-air-aem",
      exhaustId: "exhaust-borla-atak",
      brakeId: "brake-brembo-gt-6pot",
      suspensionId: "suspension-hr-springs",
      ecuId: "ecu-stage2-burble",
      mountId: "mount-poly-70a-street",
      coolingId: "cooling-peterson-dry-sump",
    },
    specsEstimate: {
      powerHp: 755,
      torqueNm: 870,
      weightKg: 1710,
      zeroToHundredSec: "3.1s",
      topSpeedKmh: 315,
    },
  },
];
